#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : pypi-wordfreq
Version  : 3.0.3
Release  : 9
URL      : https://files.pythonhosted.org/packages/ef/13/c6bad965fc32f1388694fff1cf4f16f46a4ce552604ba3f46db006cbcc5b/wordfreq-3.0.3.tar.gz
Source0  : https://files.pythonhosted.org/packages/ef/13/c6bad965fc32f1388694fff1cf4f16f46a4ce552604ba3f46db006cbcc5b/wordfreq-3.0.3.tar.gz
Summary  : Look up the frequencies of words in many languages, based on many sources of data.
Group    : Development/Tools
License  : Apache-2.0
Requires: pypi-wordfreq-python = %{version}-%{release}
Requires: pypi-wordfreq-python3 = %{version}-%{release}
BuildRequires : buildreq-distutils3
BuildRequires : pypi(poetry_core)

%description
wordfreq is a Python library for looking up the frequencies of words in many
languages, based on many sources of data.

%package python
Summary: python components for the pypi-wordfreq package.
Group: Default
Requires: pypi-wordfreq-python3 = %{version}-%{release}

%description python
python components for the pypi-wordfreq package.


%package python3
Summary: python3 components for the pypi-wordfreq package.
Group: Default
Requires: python3-core
Provides: pypi(wordfreq)
Requires: pypi(ftfy)
Requires: pypi(langcodes)
Requires: pypi(msgpack)
Requires: pypi(regex)

%description python3
python3 components for the pypi-wordfreq package.


%prep
%setup -q -n wordfreq-3.0.3
cd %{_builddir}/wordfreq-3.0.3
pushd ..
cp -a wordfreq-3.0.3 buildavx2
popd

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1666744162
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
export MAKEFLAGS=%{?_smp_mflags}
python3 -m build --wheel --skip-dependency-check --no-isolation
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
python3 -m build --wheel --skip-dependency-check --no-isolation

popd

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
pip install --root=%{buildroot} --no-deps --ignore-installed dist/*.whl
echo ----[ mark ]----
cat %{buildroot}/usr/lib/python3*/site-packages/*/requires.txt || :
echo ----[ mark ]----
pushd ../buildavx2/
export CFLAGS="$CFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export CXXFLAGS="$CXXFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FFLAGS="$FFLAGS -m64 -march=x86-64-v3 -Wl,-z,x86-64-v3 "
export FCFLAGS="$FCFLAGS -m64 -march=x86-64-v3 "
export LDFLAGS="$LDFLAGS -m64 -march=x86-64-v3 "
pip install --root=%{buildroot}-v3 --no-deps --ignore-installed dist/*.whl
popd
/usr/bin/elf-move.py avx2 %{buildroot}-v3 %{buildroot} %{buildroot}/usr/share/clear/filemap/filemap-%{name}

%files
%defattr(-,root,root,-)

%files python
%defattr(-,root,root,-)

%files python3
%defattr(-,root,root,-)
/usr/lib/python3*/*
